### PR TITLE
InvisibilityCloak updated

### PR DESCRIPTION
**Pull request by eremit4**
1) Imported only used functions
2) Defined function's description, types of outputs and parameters
3) Joined some .replace() methods in the same line
4) Alert 'Local variable substringCount might be referenced before assignment' fixed
5) Removed too many empty print() and included '\n' on the previous print
6) Replaced some joined strings to 'format' pattern into the print()
7) Shadows built-in name 'str' fixed

### CODE REVIEW

**Comment by h4wkst3r** [comment]
@eremit4 - Thank you for the pull request! This looks great. Please just make these last few updates, and then I can get this merged into the `main` branch.

* Update version to 0.5 on line 43
* Update version to 0.5 on line 510
* On line 487, those characters need moved under the "y" to complete that letter in the banner

**Comment by eremit4** [comment]
Hi @h4wkst3r!
I'm glad you liked my pull request.
I have a question: the last version of InvisibilityCloak I saw was v0.4.1 made on April 27th. What would be the modifications of v0.5?

**Comment by h4wkst3r** [comment]
The modifications would be your changes. Just trying to make sure the changes are tracked appropriately by a new version number of the tool 👍

**Comment by eremit4** [comment]
I'm sorry! I completely confused things lol
I added the changes you told me. Thanks!

**Pull request merged**
